### PR TITLE
Add travis file

### PR DESCRIPTION
**Pull request by luiscoms**

### CODE REVIEW

**Comment by ibotty** [comment]
Thank you for contributing! There is only the one issue I see. Other than that, it looks fine!

**Comment by luiscoms** [comment]
Done

**Comment by luiscoms** [comment]
hey @ibotty did you see that?

**Comment by ibotty** [comment]
Are you sure you pushed that? I only see the commit from a week ago.

**Comment by luiscoms** [comment]
The only commit in this Merge Request is the travis file. 
What is the problem with this?

**Comment by ibotty** [comment]
See the comment I made. It builds s2i in the install section. Can you change it to use the prebuild files?

**Comment by luiscoms** [comment]
I do not understand what you mean with use prebuild files.
This travis file download the `s2i` client to build and test the image

**Comment by ibotty** [comment]
`hack/build.sh` builds the s2i tool. Please use the already build tool from e.g.
https://github.com/openshift/source-to-image/releases/download/v1.1.7/source-to-image-v1.1.7-226afa1-linux-amd64.tar.gz

You can e.g. use (untested):

```shell
> curl -s https://api.github.com/repos/openshift/source-to-image/releases/latest | \
    jq '.assets[].browser_download_url'
```
to get all released files. You will have to filter for the right architecture and OS.

If you don't agree, please comment :-D.

**Comment by luiscoms** [comment]
Hey @ibotty I just updated the travis file with your suggestion

**Comment by luiscoms** [comment]
Did you saw my latest commit?

**Comment by ibotty** [comment]
I did not. Thank you.

**Pull request merged**
