### PR TITLE
Test app

### PR DESCRIPTION
**Pull request by luiscoms**
Added test-app

Run `make test`

### CODE REVIEW

**Review by ibotty — CHANGES_REQUESTED** [review]
Please remove the gitignore files.

If you need them locally, consider using a global gitignore file (with that or similar content).

**Comment by ibotty** [comment]
Looks great! Can you rebase after changing the small change request?

**Comment by luiscoms** [comment]
I Just remove the gitignore

**Comment by luiscoms** [comment]
So, do you want this merge?

**Comment by ibotty** [comment]
Can you please rebase, so the gitignore file does not even appear in the repo? If you don't know how that is possible, I can also do that.

**Comment by luiscoms** [comment]
@ibotty 

The `.gitignore` file inside test folder prevent commits on main project.

You can see that line https://github.com/ibotty/s2i-nginx/pull/2/files#diff-a6e781883513014286df21a2e0e8aaa2R75 
It init a git  repository, when tests does not pass, next run could commit on main repository.

**Comment by ibotty** [comment]
That makes sense. Can you please rebase the two commits you have into one?

**Comment by luiscoms** [comment]
Done

**Comment by ibotty** [comment]
Thank you!

**Pull request merged**
